site_name: Workshop Title

nav:
  - Workshop Introduction: index.md
  - Workshop Overview: overview.md
  - Solution Architecture: architecture.md
  - Security Considerations: security.md
  - Getting Started: getting-started.md
  # - Workshop Setup:
  #   - BUILD Attendees: introduction-event.md
  #   - Self-Guided Learners: introduction-self-guided.md

  # - Lab 1 Grounding LLMs with MCP: lab-1-mcp_intro.md
  - Lab 1 Opening the Workshop: lab-1-open-workshop.md
  - Lab 2 ....: lab-2.md
  - Lab 6 Finishing Up: lab-6-finishing-up.md
  - Summary: summary.md
  - Resources: resources.md
  - About: about.md
  # - Deployment: deployment.md
  # - Troubleshooting: troubleshooting.md


plugins:
  - glightbox
  - include-markdown

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css


